name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 */4 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ogg
    - uses: https://github.com/Sadik-Hossain/github-profile-terminal-action@main
      with:
        feed_url: https://www.liam-galvin.co.uk/feed.xml
        twitter_username: SadikHossainSam
        theme: dark
        token: ${{ secrets.GH_PAT }}
